FileVersion = 1
Dependencies = {corlib = "*", Beefy2D = "*", SDL2 = "*"}

[Project]
Name = "StubUI"
TargetType = "BeefDynLib"
StartupObject = "Program"
DefaultNamespace = "BIStubUI"

[Configs.Debug.Win64]
TargetDirectory = "$(WorkspaceDir)/../dist"
TargetName = "$(ProjectName)_d"
OtherLinkFlags = "$(LinkFlags) BeefySysLib64_d.lib"
BeefLibType = "DynamicDebug"
DebugCommand = "$(WorkspaceDir)\\..\\dist\\Stub_d.exe"

[Configs.Release.Win64]
TargetDirectory = "$(WorkspaceDir)/../dist"

[Configs.Paranoid.Win64]
TargetDirectory = "$(WorkspaceDir)/../dist"

[Configs.Test.Win64]
TargetDirectory = "$(WorkspaceDir)/../dist"
