FileVersion = 1
Projects = {mintest = {Path = "."}, minlib = {Path = "minlib"}, LibA = {Path = "LibA"}, LibB = {Path = "LibB"}, mintest2 = {Path = "mintest2"}}
Locked = ["mintest2"]

[Workspace]
StartupProject = "mintest"

[Configs.Debug.Win32]
BfOptimizationLevel = "OgPlus"
InitLocalVariables = true
IntermediateType = "ObjectAndIRCode"
ConfigSelections = {mintest2 = {Enabled = false}}

[[Configs.Debug.Win32.DistinctOptions]]
Filter = "NoFrame"

[Configs.Debug.Win64]
IntermediateType = "ObjectAndIRCode"
COptimizationLevel = "Og"

[[Configs.Debug.Win64.DistinctOptions]]
Filter = "System.String"

[Configs.Debug.WinFart]
Toolset = "GNU"
EmitDebugInfo = "No"
EmitDynamicCastCheck = false
EnableObjectDebugFlags = false
EmitObjectAccessCheck = false
EnableRealtimeLeakCheck = false
AllowHotSwapping = false
AllocStackTraceDepth = 0

[Configs.Debug.Linux64]
Toolset = "GNU"
EnableRealtimeLeakCheck = false

[Configs.Debug.macOS]
Toolset = "GNU"
EnableRealtimeLeakCheck = false

[Configs.Debug.iOS]
Toolset = "GNU"
EnableRealtimeLeakCheck = false
IntermediateType = "Bitcode"

[Configs.Debug.aarch64-none-linux-android21]
Toolset = "GNU"
EnableRealtimeLeakCheck = false

[Configs.Release.Win32]
Toolset = "GNU"
BfOptimizationLevel = "OgPlus"
EmitDebugInfo = "No"
AllocStackTraceDepth = 0
IntermediateType = "ObjectAndIRCode"

[Configs.Release.Win64]
BfSIMDSetting = "SSE3"
AllocStackTraceDepth = 0
IntermediateType = "ObjectAndIRCode"
COptimizationLevel = "O3"

[Configs.Release.WinFart]
Toolset = "GNU"
BfOptimizationLevel = "O0"
EmitDebugInfo = "No"
AllocStackTraceDepth = 0
IncrementalBuild = true
COptimizationLevel = "O0"

[Configs.Release.Linux64]
Toolset = "GNU"

[Configs.Release.macOS]
Toolset = "GNU"

[Configs.Release.iOS]
Toolset = "GNU"
IntermediateType = "Bitcode"

[Configs.Release.aarch64-none-linux-android21]
Toolset = "GNU"

[Configs.Test.Win32]
Toolset = "GNU"
BfSIMDSetting = "None"
EmitDebugInfo = "No"
EmitDynamicCastCheck = false
EnableObjectDebugFlags = false
EmitObjectAccessCheck = false
EnableRealtimeLeakCheck = false
AllocStackTraceDepth = 0
CSIMDSetting = "None"
COptimizationLevel = "O2"
ConfigSelections = {mintest = {Config = "Debug"}}

[Configs.Test.Win64]
EmitDynamicCastCheck = false
EnableObjectDebugFlags = false
EmitObjectAccessCheck = false
EnableRealtimeLeakCheck = false
AllowHotSwapping = false
AllocStackTraceDepth = 0
COptimizationLevel = "O2"
ConfigSelections = {mintest = {Config = "Debug"}}

[Configs.Test.WinFart]
Toolset = "GNU"
BuildKind = "Normal"
EmitDebugInfo = "No"
EmitDynamicCastCheck = false
EnableObjectDebugFlags = false
EmitObjectAccessCheck = false
EnableRealtimeLeakCheck = false
AllowHotSwapping = false
AllocStackTraceDepth = 0
COptimizationLevel = "O2"

[Configs.Test.Linux64]
Toolset = "GNU"
EnableRealtimeLeakCheck = false
COptimizationLevel = "O2"

[Configs.Test.macOS]
Toolset = "GNU"
EnableRealtimeLeakCheck = false
COptimizationLevel = "O2"

[Configs.Test.iOS]
Toolset = "GNU"
EnableRealtimeLeakCheck = false
IntermediateType = "Bitcode"
COptimizationLevel = "O2"

[Configs.Test.aarch64-none-linux-android21]
Toolset = "GNU"
EnableRealtimeLeakCheck = false
COptimizationLevel = "O2"

[Configs.Paranoid.Win32]
Toolset = "GNU"
EmitDynamicCastCheck = false
EnableObjectDebugFlags = false
EmitObjectAccessCheck = false
EnableRealtimeLeakCheck = false
EnableSideStack = false
COptimizationLevel = "O2"

[Configs.Paranoid.Win64]
Toolset = "GNU"
EmitDynamicCastCheck = false
EnableObjectDebugFlags = false
EmitObjectAccessCheck = false
EnableRealtimeLeakCheck = false
EnableSideStack = false
COptimizationLevel = "O2"
ConfigSelections = {mintest2 = {Enabled = false}}

[Configs.Paranoid.WinFart]
Toolset = "GNU"
EmitDebugInfo = "No"
EmitDynamicCastCheck = false
EnableObjectDebugFlags = false
EmitObjectAccessCheck = false
EnableRealtimeLeakCheck = false
EnableSideStack = false
AllowHotSwapping = false
AllocStackTraceDepth = 0
COptimizationLevel = "O2"

[Configs.Paranoid.Linux64]
Toolset = "GNU"
EnableRealtimeLeakCheck = false
EnableSideStack = false
COptimizationLevel = "O2"

[Configs.Paranoid.macOS]
Toolset = "GNU"
EnableRealtimeLeakCheck = false
EnableSideStack = false
COptimizationLevel = "O2"

[Configs.Paranoid.iOS]
Toolset = "GNU"
EnableRealtimeLeakCheck = false
EnableSideStack = false
IntermediateType = "Bitcode"
COptimizationLevel = "O2"

[Configs.Paranoid.aarch64-none-linux-android21]
Toolset = "GNU"
EnableRealtimeLeakCheck = false
EnableSideStack = false
COptimizationLevel = "O2"
